server: 91.217.189.21
port: 6667
channels: 
  - "#ehwas"
  - "#Elepanten"
  - "#pr0gr.am"
info: 
  nick: pr0gram
  user: pr0gram
  name: pr0gram
admins: 
  - ".+@kenansulayman.users.quakenet.org"
bcnicks: 
  - apx
ignore: 
  users: 
    - ".+@unaffiliated/something"
cmdchar: "!"
vhost: null
modules: 
  - admin
  - log
  - pr0gram
__file: /Volumes/Hyperstore/pr0gr.am/bot/config.yaml
